FROM alpine:3.11.6

RUN apk update
RUN apk add nginx
RUN apk add openssl ca-certificates
RUN apk add php7 php7-fpm php7-opcache
RUN apk add php7-gd php7-mysqli php7-zlib php7-curl php7-json php7-ctype