
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pmysql-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv0001/
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysql-volume-claim
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
            - name: mysql
              image: my_mysql
              imagePullPolicy: Never
              ports:
              - containerPort: 3306
              volumeMounts:
              - name: mysql-vc
                mountPath: /var/lib/mysql
            volumes:
            - name: mysql-vc
              persistentVolumeClaim:
                  claimName: mysql-volume-claim


             