apiVersion: apps/v1
kind: Deployment
metadata:
    name: wordpress
spec:
    replicas: 1
    selector:
        matchLabels:
            app: wordpress
    template:
        metadata:
            labels:
                app: wordpress
        spec:
            containers:
            - name: wordpress
              image: my_wordpress
              imagePullPolicy: Never
              ports:
              - containerPort: 5050