NAME = checker 
NAME1 = push_swap


SRCS = checker.c


OBJS = $(SRCS:.c=.o)

SRCS1 = push_swap.c


OBJS1 = $(SRCS1:.c=.o)


CC = gcc

#-fsanitize=address 
CFLAGS = -g -fsanitize=address   #-Wall -Wextra -Werror 


LFAGS = -L. ./libft/libft.a -L. ./srcs/pushswap.a


all: $(NAME)



$(NAME):$(OBJS)
	make -C srcs
	$(CC)    $(CFLAGS)   $(LFAGS) $(SRCS) -o $(NAME)
	$(CC)    $(CFLAGS)   $(LFAGS) $(SRCS1) -o $(NAME1)
	rm -rf *.dSYM
	make clean > /dev/null


clean:
	rm -f *.o
	rm -f srcs/*.o
	/bin/rm -f $(OBJS)

fclean: clean
	/bin/rm -f $(NAME)

re : fclean all