apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
<<<<<<< HEAD
      - 192.168.99.100-192.168.99.200
=======
      - 192.168.99.105-192.168.99.105
>>>>>>> e3c6c445707464786619b696469b758e7fd9e7f5
